//
//  MainPageViewModel.swift
//  OZON
//
//  Created by Macbook on 07.08.2023.
//

import Foundation
class MainPageViewModel:ObservableObject {
    
    static let shared = MainPageViewModel()
    
    var products = [
        Product(id: "1",
                title: "Картина по номерам Шрек Мем, 40 х 40 см",
                imageURL: "shrek",
                price: 1375, rating: 5,
                reviews: 12,
                descript: "Количество красок от 18 до 24. Картина раскрашивается без смешивания красок. В комплекте: натуральный хлопковый холст, баночки с акриловыми красками на водной основе, 2 кисти из качественного нейлона, схема раскашивания, инструкция."),
        Product(id: "2",
                title: "Аксессуар для курицы, эмуляция лап динозавра",
                imageURL: "chicken",
                price: 1178, rating: 5,
                reviews: 999,
                descript: "Идеально подходит для всех видов кур, и даже может быть использован для уток, индюков и других птиц."),
        Product(id: "3",
                title: "Игрушка Лягушонок Пепе 45 см",
                imageURL: "pepe",
                price: 823, rating: 5,
                reviews: 40,
                descript: "Лягушка Пепе подозревает."),
        Product(id: "4",
                title: "Игра на меткость, Дартс 2.0, двигающаяся мишень",
                imageURL: "game",
                price: 249, rating: 3,
                reviews: 7,
                descript: "Отличный подарок для ребенка или любимой. Игра сбизит с семьей и позволит хорошо провести время."),
        Product(id: "5",
                title: "Костюм Пива, мужской, вечеринка",
                imageURL: "beerSuit",
                price: 2130, rating: 5,
                reviews: 120,
                descript: "Будь самым красивым на этом празднике жизни в нашем пивном костюме!"),
        Product(id: "6",
                title: "Акриловый брелок для ключей Hasbulla",
                imageURL: "hasbik",
                price: 292, rating: 5,
                reviews: 1,
                descript: "Будь всегда под защитой с нашим брелком-оберегом."),
        Product(id: "7",
                title: "Солнцезащитные очки для кошек",
                imageURL: "glasses",
                price: 130, rating: 4,
                reviews: 568,
                descript: "Модные красные темные очки в форме сердца, с защитой от ультрафиолета, для собак и щенков"),
        Product(id: "8",
                title: "Кулон Зуб, оберег от сглаза",
                imageURL: "tooth",
                price: 3220, rating: 3,
                reviews: 17,
                descript: "Подвеска из настоящего зуба - это небанальный подарок для любимого."),
        Product(id: "9",
                title: "Качели для хомяка, качели для крысы 30см",
                imageURL: "hammock",
                price: 205, rating: 2,
                reviews: 8,
                descript: "Чего в вашей жизни точно не хватало - так это малюсеньких качелей для вашего хомяка. Скорее всего, хомяк тоже этого не подозревал."),
        Product(id: "10",
                title: "Носки белые длинные 43-46р",
                imageURL: "cheeps",
                price: 270, rating: 3,
                reviews: 13,
                descript: "Просто носки."),
        Product(id: "11",
                title: "Футболка I love kids",
                imageURL: "tkids",
                price: 520, rating: 4,
                reviews: 122,
                descript: "Футболка мужская. Материал - 100% хлопок."),
        Product(id: "12",
                title: "Футболка Андрей мужская",
                imageURL: "tkir",
                price: 1225, rating: 3,
                reviews: 2,
                descript: "Именная футболка, отлично подойдет в подарок вашему другу Антону."),
        Product(id: "13",
                title: "Ботинки Balenciaga новые оригинальные",
                imageURL: "shoes",
                price: 6247, rating: 5,
                reviews: 324,
                descript: "Ботинки изготовлены из качественной ЭКО замши. Благодаря перфорации, отлично дышат."),
        Product(id: "14",
                title: "Кот-банан 38 см",
                imageURL: "bananaCat",
                price: 520, rating: 4,
                reviews: 122,
                descript: "Банана-кэт 38 см от Кирилла Плюша! Игрушка станет преданным другом для вашего ребенка на все времена! Не вызывает аллергии, легко стирается, не боится растяжения."),
        Product(id: "15",
                title: "Футболка Кот мужская",
                imageURL: "tcat",
                price: 1270, rating: 3,
                reviews: 388,
                descript: "Футболка мужская смешной кот в костюме.")]
    
    var services = [
        Service(id: "1", name: "Карта Ozon банка",
                image: "bank"),
        Service(id: "2", name: "Билеты, Отели, Туры",
                image: "OzonTravel"),
        Service(id: "3", name: "Ликвидация",
                image: "liquid"),
        Service(id: "4", name: "Все для школы",
                image: "school"),
        Service(id: "5", name: "Акции и скидки",
                image: "sales"),
        Service(id: "6", name: "Одежда и обувь",
                image: "cloth"),
        Service(id: "7", name: "Дом и сад",
                image: "home"),
        Service(id: "8", name: "Ozon Premium",
                image: "premium"),
        Service(id: "9", name: "Электроника",
                image: "electronic"),
        Service(id: "10", name: "Сертификаты",
                image: "certificates")]
    
}
